# Generated by Django 6.0.5 on 2026-05-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=10)),
                ('status', models.CharField(choices=[('in_service', 'In Service'), ('under_maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service')], db_index=True, default='in_service', max_length=20)),
                ('critical', models.BooleanField(db_index=True, default=False)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['next_due_date'],
            },
        ),
    ]
